### ISSUE TITLE
LR finder for regression problems

### ISSUE THREAD

**Issue by Stoops-ML** [davidtvs/pytorch-lr-finder#34]
Is this code useable on regression problems, or only classification problems? I've been trying to get it to work for sometime with no success.

**Comment by davidtvs** [comment]
Should work. What exactly were you not able to get working?

**Comment by Stoops-ML** [comment]
Here's the error:

Traceback (most recent call last):
  File "/Users/danielstoops/Desktop/Work/ML/projects/aerofoils/run_CNN.py", line 149, in <module>
    lr_finder.range_test(train_loader, end_lr=100, num_iter=100)
  File "/usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch_lr_finder/lr_finder.py", line 189, in range_test
    loss = self._train_batch(iter_wrapper, accumulation_steps)
  File "/usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch_lr_finder/lr_finder.py", line 242, in _train_batch
    loss = self.criterion(outputs, labels)
  File "/usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 782, in forward
    return F.smooth_l1_loss(input, target, reduction=self.reduction)
  File "/usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py", line 2153, in smooth_l1_loss
    if not (target.size() == input.size()):
AttributeError: 'tuple' object has no attribute 'size'

And my Code
`criterion_ClCd = nn.SmoothL1Loss()
criterion_angle = nn.SmoothL1Loss()
optimiser = torch.optim.SGD(model.parameters(), lr=learning_rate)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimiser, 'min', patience=5)

if find_LR:
    lr_finder = LRFinder(model, optimiser, criterion_ClCd, device=device)
    lr_finder.range_test(train_loader, end_lr=100, num_iter=100)
    lr_finder.plot()  # to inspect the loss-learning rate graph
    lr_finder.reset()  # to reset the model and optimizer to their initial state`

I assume I'm getting this error because my the output from my dataset class is a tuple:
```
class AerofoilDataset(Dataset):
...
def __getitem__(self, item):
...
return self.x[item].view(self.num_channels, self.input_size), self.y[item], self.aerofoil[item]
```

**Comment by Stoops-ML** [comment]
Hi, I've been working on this for a few hours now and I figured out that I my forward method was outputting a tuple and not a single tensor. Now your learning rate finder works very well.

Thank you for your very impressive work and for your speedy response to my query. I'm just starting out in deep learning, hopefully I'll be able to get to your level someday
