### ISSUE TITLE
please make it installable using pip

### ISSUE THREAD

**Issue by Vozf** [davidtvs/pytorch-lr-finder#4]
Currently it can't be installed with  `pip install git+https://github.com/davidtvs/pytorch-lr-finder`
```
Collecting git+https://github.com/davidtvs/pytorch-lr-finder
  Cloning https://github.com/davidtvs/pytorch-lr-finder to /tmp/pip-req-build-bies1fy1
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/a_yaroshevich/anaconda3/envs/rnd/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-bies1fy1/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-bies1fy1/
```
For it to work you need to create setup.py and list there your dependencies.plus modules need to be correct

**Comment by davidtvs** [comment]
Will do it soon, thanks for bringing it up

**Comment by davidtvs** [comment]
Should be working now:
``pip install torch-lr-finder``
